
"""
Module that deals with color ramps

This product includes color specifications and designs developed by 
Cynthia Brewer (http://colorbrewer.org/).
"""
# This file is part of 'Viewer' - a simple Raster viewer
# Copyright (C) 2012  Sam Gillingham
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import numpy

# init our dictionary of data
# longest list of colors for each name
# from http://colorbrewer.org/
# generated by colorbrewer2py.py
RAMP = {}
RAMP['Blues'] = {'type' : 'Sequential'}
RAMP['Blues']['r'] = '247 222 198 158 107 66 33 8 8'
RAMP['Blues']['g'] = '251 235 219 202 174 146 113 81 48'
RAMP['Blues']['b'] = '255 247 239 225 214 198 181 156 107'
RAMP['Greys'] = {'type' : 'Sequential'}
RAMP['Greys']['r'] = '255 240 217 189 150 115 82 37 0'
RAMP['Greys']['g'] = '255 240 217 189 150 115 82 37 0'
RAMP['Greys']['b'] = '255 240 217 189 150 115 82 37 0'
RAMP['RdBu'] = {'type' : 'Diverging'}
RAMP['RdBu']['r'] = '103 178 214 244 253 247 209 146 67 33 5'
RAMP['RdBu']['g'] = '0 24 96 165 219 247 229 197 147 102 48'
RAMP['RdBu']['b'] = '31 43 77 130 199 247 240 222 195 172 97'
RAMP['RdYlBu'] = {'type' : 'Diverging'}
RAMP['RdYlBu']['r'] = '165 215 244 253 254 255 224 171 116 69 49'
RAMP['RdYlBu']['g'] = '0 48 109 174 224 255 243 217 173 117 54'
RAMP['RdYlBu']['b'] = '38 39 67 97 144 191 248 233 209 180 149'
RAMP['RdYlGn'] = {'type' : 'Diverging'}
RAMP['RdYlGn']['r'] = '165 215 244 253 254 255 217 166 102 26 0'
RAMP['RdYlGn']['g'] = '0 48 109 174 224 255 239 217 189 152 104'
RAMP['RdYlGn']['b'] = '38 39 67 97 139 191 139 106 99 80 55'
RAMP['Reds'] = {'type' : 'Sequential'}
RAMP['Reds']['r'] = '255 254 252 252 251 239 203 165 103'
RAMP['Reds']['g'] = '245 224 187 146 106 59 24 15 0'
RAMP['Reds']['b'] = '240 210 161 114 74 44 29 21 13'
RAMP['Spectral'] = {'type' : 'Diverging'}
RAMP['Spectral']['r'] = '158 213 244 253 254 255 230 171 102 50 94'
RAMP['Spectral']['g'] = '1 62 109 174 224 255 245 221 194 136 79'
RAMP['Spectral']['b'] = '66 79 67 97 139 191 152 164 165 189 162'
RAMP['YlGnBu'] = {'type' : 'Sequential'}
RAMP['YlGnBu']['r'] = '255 237 199 127 65 29 34 37 8'
RAMP['YlGnBu']['g'] = '255 248 233 205 182 145 94 52 29'
RAMP['YlGnBu']['b'] = '217 177 180 187 196 192 168 148 88'
RAMP['YlOrRd'] = {'type' : 'Sequential'}
RAMP['YlOrRd']['r'] = '255 255 254 254 253 252 227 189 128'
RAMP['YlOrRd']['g'] = '255 237 217 178 141 78 26 0 0'
RAMP['YlOrRd']['b'] = '204 160 118 76 60 42 28 38 38'

def getRampsForDisplay():
    """
    Returns a list of (name, displayname) tuples for
    populating Combo boxes. Sorted by type
    """
    # sort by stype
    rampDict = {}
    for key in RAMP:
        rampType = RAMP[key]['type']
        if rampType in rampDict:
            rampDict[rampType].append(key)
        else:
            rampDict[rampType] = [key]

    display = []
    for rampType in rampDict:
        for name in rampDict[rampType]:
            title = "%s (%s)" % (name, rampType)
            display.append((name, title))
    return display

def getLUTForRamp(code, name, lutsize):
    """
    Returns an LUT for the specified color and name
    """
    # get the data as string
    colstr = RAMP[name][code]
    # turn it into a list of floats
    # numpy.interp() needs floats
    colList = [float(x) for x in colstr.split()]
    # the x-values of the observations
    # evenly spaced 0-255 with len(colList) obs
    xobs = numpy.linspace(0, 255, len(colList))
    # create an array from our list
    yobs = numpy.array(colList)
    # values to interpolate at 0-255
    # same size as the lut
    xinterp = numpy.linspace(0, 255, lutsize)
    # do the interp
    yinterp = numpy.interp(xinterp, xobs, yobs)
    # return as 8 bit int
    return yinterp.astype(numpy.uint8)
